-- 20260702152534 create_regulatory_kb_store

-- regulatory-kb (OKF 법령 요약 레이어) 전용 스토어. document_chunks(조문 원문)와 별개.
create table if not exists public.kb_documents (
  id                   bigint generated by default as identity primary key,
  dedup_key            text,
  title                text not null,
  concept_type         text,           -- Law/Regulation/Notice/Guideline/Procedure/Glossary
  family               text,           -- laws/<family>/... 경로 그룹
  law_type             text,
  law_number           text,
  enforcement_date     text,
  competent_authority  text,
  status               text not null default 'current',   -- current | superseded
  superseded_by        text,
  path                 text not null,  -- 번들 상대경로 = 문서 정체 키
  description          text,
  body_md              text,
  created_at           timestamptz default now()
);
create unique index if not exists kb_documents_path_uidx on public.kb_documents(path);
create index if not exists kb_documents_dedup_key_idx on public.kb_documents(dedup_key);
create index if not exists kb_documents_status_idx on public.kb_documents(status);

create table if not exists public.kb_chunks (
  id          bigint generated by default as identity primary key,
  doc_id      bigint not null references public.kb_documents(id) on delete cascade,
  chunk_idx   integer,
  content     text not null,
  embedding   vector(1024),
  created_at  timestamptz default now()
);
create index if not exists kb_chunks_doc_id_idx on public.kb_chunks(doc_id);
create index if not exists kb_chunks_content_trgm_idx on public.kb_chunks using gin (content gin_trgm_ops);
create index if not exists kb_chunks_embedding_hnsw_idx on public.kb_chunks using hnsw (embedding vector_cosine_ops) with (m='16', ef_construction='64');

-- RLS: 대시보드 anon 조회 허용(검색). insert/update는 service key(적재 스크립트)가 RLS 우회.
alter table public.kb_documents enable row level security;
alter table public.kb_chunks enable row level security;
drop policy if exists kb_documents_anon_select on public.kb_documents;
create policy kb_documents_anon_select on public.kb_documents for select to anon using (true);
drop policy if exists kb_chunks_anon_select on public.kb_chunks;
create policy kb_chunks_anon_select on public.kb_chunks for select to anon using (true);

-- 시맨틱 검색(pgvector 코사인). 기본 current만.
create or replace function public.match_kb_chunks_semantic(
  query_embedding vector(1024),
  match_threshold float default 0.35,
  match_count int default 6,
  only_current boolean default true
) returns table(
  doc_id bigint, title text, law_type text, law_number text,
  enforcement_date text, status text, concept_type text, path text,
  chunk_idx int, content text, similarity float
) language sql stable as $$
  select d.id, d.title, d.law_type, d.law_number, d.enforcement_date,
         d.status, d.concept_type, d.path, c.chunk_idx, c.content,
         (1 - (c.embedding <=> query_embedding))::float as similarity
  from public.kb_chunks c
  join public.kb_documents d on d.id = c.doc_id
  where c.embedding is not null
    and (not only_current or d.status = 'current')
    and (1 - (c.embedding <=> query_embedding)) > match_threshold
  order by c.embedding <=> query_embedding
  limit match_count;
$$;

-- 문자열 유사도(trgm) 검색. 기본 current만.
create or replace function public.search_kb_chunks_trgm(
  query_text text,
  match_threshold float default 0.10,
  match_count int default 6,
  only_current boolean default true
) returns table(
  doc_id bigint, title text, law_type text, law_number text,
  enforcement_date text, status text, concept_type text, path text,
  chunk_idx int, content text, trgm_score float
) language sql stable as $$
  select d.id, d.title, d.law_type, d.law_number, d.enforcement_date,
         d.status, d.concept_type, d.path, c.chunk_idx, c.content,
         extensions.word_similarity(query_text, c.content)::float as trgm_score
  from public.kb_chunks c
  join public.kb_documents d on d.id = c.doc_id
  where (not only_current or d.status = 'current')
    and extensions.word_similarity(query_text, c.content) > match_threshold
  order by trgm_score desc
  limit match_count;
$$;

grant execute on function public.match_kb_chunks_semantic(vector, float, int, boolean) to anon;
grant execute on function public.search_kb_chunks_trgm(text, float, int, boolean) to anon;;
