-- 20260911024434 law_terms_table

-- 법적 용어 정의(#156): 현행 법령·고시의 정의 조문(제N조(정의)·(용어의 정의)·(용어정의)·(용어의 뜻))에서 원문 그대로 추출.
-- 파생 테이블 — law_terms_sync.py가 매일 11:00 KST(law_crawl.yml)에 전량 재생성. SQL로 직접 편집 금지.
create table if not exists public.law_terms (
  id             bigint generated by default as identity primary key,
  term           text not null,
  term_key       text not null,
  term_alias     text,
  law_name       text not null,
  full_name      text,
  law_type       text not null default '기타',
  doc_name       text not null,
  doc_category   text,
  article_no     text not null,
  article_key    text,
  item_no        text not null,
  definition     text not null,
  law_no         text,
  effective_date text,
  synced_at      timestamptz not null default now(),
  constraint law_terms_uq unique (doc_name, article_no, item_no)
);
create index if not exists law_terms_term_key_idx on public.law_terms (term_key);
create index if not exists law_terms_law_type_idx on public.law_terms (law_type);
create index if not exists law_terms_doc_idx      on public.law_terms (doc_name);
create index if not exists law_terms_synced_idx   on public.law_terms (synced_at);
alter table public.law_terms enable row level security;
create policy law_terms_sel on public.law_terms for select to anon, authenticated using (true);
grant select on public.law_terms to anon, authenticated;;
